<<<<<<< HEAD
# Generated by Django 3.1.4 on 2021-01-22 07:01
=======
# Generated by Django 3.1.4 on 2021-01-20 08:32
>>>>>>> 384a2ba905e4c67b2195ee2ba53f930ca6fde4d0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('published_at', models.DateField(auto_now_add=True)),
=======
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
>>>>>>> 384a2ba905e4c67b2195ee2ba53f930ca6fde4d0
            ],
        ),
    ]
