# Generated by Django 3.1.4 on 2021-01-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210122_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
    ]
