# Generated by Django 3.1.4 on 2021-01-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210124_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='published_at',
            new_name='date',
        ),
    ]
