# Generated by Django 3.1.4 on 2021-01-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_books_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
